/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedVagasIndexRouteImport } from './routes/_authenticated/vagas/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRelatoriosIndexRouteImport } from './routes/_authenticated/relatorios/index'
import { Route as AuthenticatedVagasNovaRouteImport } from './routes/_authenticated/vagas/nova'
import { Route as AuthenticatedVagasImportarRouteImport } from './routes/_authenticated/vagas/importar'
import { Route as AuthenticatedVagasVagaIdRouteImport } from './routes/_authenticated/vagas/$vagaId'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedVagasVagaIdEditarRouteImport } from './routes/_authenticated/vagas/$vagaId.editar'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVagasIndexRoute = AuthenticatedVagasIndexRouteImport.update({
  id: '/vagas/',
  path: '/vagas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRelatoriosIndexRoute =
  AuthenticatedRelatoriosIndexRouteImport.update({
    id: '/relatorios/',
    path: '/relatorios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVagasNovaRoute = AuthenticatedVagasNovaRouteImport.update({
  id: '/vagas/nova',
  path: '/vagas/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVagasImportarRoute =
  AuthenticatedVagasImportarRouteImport.update({
    id: '/vagas/importar',
    path: '/vagas/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVagasVagaIdRoute =
  AuthenticatedVagasVagaIdRouteImport.update({
    id: '/vagas/$vagaId',
    path: '/vagas/$vagaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVagasVagaIdEditarRoute =
  AuthenticatedVagasVagaIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedVagasVagaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/vagas/$vagaId': typeof AuthenticatedVagasVagaIdRouteWithChildren
  '/vagas/importar': typeof AuthenticatedVagasImportarRoute
  '/vagas/nova': typeof AuthenticatedVagasNovaRoute
  '/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/vagas/': typeof AuthenticatedVagasIndexRoute
  '/vagas/$vagaId/editar': typeof AuthenticatedVagasVagaIdEditarRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/vagas/$vagaId': typeof AuthenticatedVagasVagaIdRouteWithChildren
  '/vagas/importar': typeof AuthenticatedVagasImportarRoute
  '/vagas/nova': typeof AuthenticatedVagasNovaRoute
  '/relatorios': typeof AuthenticatedRelatoriosIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/vagas': typeof AuthenticatedVagasIndexRoute
  '/vagas/$vagaId/editar': typeof AuthenticatedVagasVagaIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/vagas/$vagaId': typeof AuthenticatedVagasVagaIdRouteWithChildren
  '/_authenticated/vagas/importar': typeof AuthenticatedVagasImportarRoute
  '/_authenticated/vagas/nova': typeof AuthenticatedVagasNovaRoute
  '/_authenticated/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/vagas/': typeof AuthenticatedVagasIndexRoute
  '/_authenticated/vagas/$vagaId/editar': typeof AuthenticatedVagasVagaIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/appearance'
    | '/vagas/$vagaId'
    | '/vagas/importar'
    | '/vagas/nova'
    | '/relatorios/'
    | '/settings/'
    | '/vagas/'
    | '/vagas/$vagaId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/appearance'
    | '/vagas/$vagaId'
    | '/vagas/importar'
    | '/vagas/nova'
    | '/relatorios'
    | '/settings'
    | '/vagas'
    | '/vagas/$vagaId/editar'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/vagas/$vagaId'
    | '/_authenticated/vagas/importar'
    | '/_authenticated/vagas/nova'
    | '/_authenticated/relatorios/'
    | '/_authenticated/settings/'
    | '/_authenticated/vagas/'
    | '/_authenticated/vagas/$vagaId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vagas/': {
      id: '/_authenticated/vagas/'
      path: '/vagas'
      fullPath: '/vagas/'
      preLoaderRoute: typeof AuthenticatedVagasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/relatorios/': {
      id: '/_authenticated/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vagas/nova': {
      id: '/_authenticated/vagas/nova'
      path: '/vagas/nova'
      fullPath: '/vagas/nova'
      preLoaderRoute: typeof AuthenticatedVagasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vagas/importar': {
      id: '/_authenticated/vagas/importar'
      path: '/vagas/importar'
      fullPath: '/vagas/importar'
      preLoaderRoute: typeof AuthenticatedVagasImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vagas/$vagaId': {
      id: '/_authenticated/vagas/$vagaId'
      path: '/vagas/$vagaId'
      fullPath: '/vagas/$vagaId'
      preLoaderRoute: typeof AuthenticatedVagasVagaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vagas/$vagaId/editar': {
      id: '/_authenticated/vagas/$vagaId/editar'
      path: '/editar'
      fullPath: '/vagas/$vagaId/editar'
      preLoaderRoute: typeof AuthenticatedVagasVagaIdEditarRouteImport
      parentRoute: typeof AuthenticatedVagasVagaIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedVagasVagaIdRouteChildren {
  AuthenticatedVagasVagaIdEditarRoute: typeof AuthenticatedVagasVagaIdEditarRoute
}

const AuthenticatedVagasVagaIdRouteChildren: AuthenticatedVagasVagaIdRouteChildren =
  {
    AuthenticatedVagasVagaIdEditarRoute: AuthenticatedVagasVagaIdEditarRoute,
  }

const AuthenticatedVagasVagaIdRouteWithChildren =
  AuthenticatedVagasVagaIdRoute._addFileChildren(
    AuthenticatedVagasVagaIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedVagasVagaIdRoute: typeof AuthenticatedVagasVagaIdRouteWithChildren
  AuthenticatedVagasImportarRoute: typeof AuthenticatedVagasImportarRoute
  AuthenticatedVagasNovaRoute: typeof AuthenticatedVagasNovaRoute
  AuthenticatedRelatoriosIndexRoute: typeof AuthenticatedRelatoriosIndexRoute
  AuthenticatedVagasIndexRoute: typeof AuthenticatedVagasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedVagasVagaIdRoute: AuthenticatedVagasVagaIdRouteWithChildren,
  AuthenticatedVagasImportarRoute: AuthenticatedVagasImportarRoute,
  AuthenticatedVagasNovaRoute: AuthenticatedVagasNovaRoute,
  AuthenticatedRelatoriosIndexRoute: AuthenticatedRelatoriosIndexRoute,
  AuthenticatedVagasIndexRoute: AuthenticatedVagasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
